"""baseline schema

Revision ID: 0001
Revises: 
Create Date: 2026-06-10 01:29:29.526896
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anon_session_profiles',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('taste_vector', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('movies',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('title_norm', sa.String(length=512), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('genres', sa.JSON(), nullable=False),
    sa.Column('poster_url', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('idx')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_title_norm'), ['title_norm'], unique=False)
        batch_op.create_index(batch_op.f('ix_movies_tmdb_id'), ['tmdb_id'], unique=False)

    op.create_table('swipe_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('time_on_card_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('swipe_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_swipe_events_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_events_tmdb_id'), ['tmdb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_swipe_events_user_id'), ['user_id'], unique=False)

    op.create_table('user_profiles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('taste_vector', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('user_saved_titles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('rec_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_saved_titles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_saved_titles_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_saved_titles_user_id'), ['user_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=128), nullable=True),
    sa.Column('google_sub', sa.String(length=64), nullable=True),
    sa.Column('apple_sub', sa.String(length=64), nullable=True),
    sa.Column('display_name', sa.String(length=128), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_apple_sub'), ['apple_sub'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_apple_sub'))

    op.drop_table('users')
    with op.batch_alter_table('user_saved_titles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_saved_titles_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_saved_titles_movie_id'))

    op.drop_table('user_saved_titles')
    op.drop_table('user_profiles')
    with op.batch_alter_table('swipe_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_swipe_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_events_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_swipe_events_session_id'))

    op.drop_table('swipe_events')
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_movies_title_norm'))
        batch_op.drop_index(batch_op.f('ix_movies_title'))
        batch_op.drop_index(batch_op.f('ix_movies_movie_id'))

    op.drop_table('movies')
    op.drop_table('anon_session_profiles')
    # ### end Alembic commands ###
