"""providers and onboarding

Revision ID: 0002
Revises: 0001
Create Date: 2026-06-10 01:40:12.367686
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('title_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('title_providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_title_providers_provider_id'), ['provider_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_title_providers_tmdb_id'), ['tmdb_id'], unique=False)

    op.create_table('user_providers',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id', 'provider_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so existing rows backfill to false on Postgres.
        batch_op.add_column(
            sa.Column('onboarding_completed', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('onboarding_completed')

    op.drop_table('user_providers')
    with op.batch_alter_table('title_providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_title_providers_tmdb_id'))
        batch_op.drop_index(batch_op.f('ix_title_providers_provider_id'))

    op.drop_table('title_providers')
    # ### end Alembic commands ###
