"""letterboxd

Revision ID: 0003
Revises: 0002
Create Date: 2026-06-10 01:48:47.811576
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('tmdb_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('external_ratings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_external_ratings_movie_id'), ['movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_external_ratings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('letterboxd_username', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('letterboxd_username')

    with op.batch_alter_table('external_ratings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_external_ratings_user_id'))
        batch_op.drop_index(batch_op.f('ix_external_ratings_movie_id'))

    op.drop_table('external_ratings')
    # ### end Alembic commands ###
